name    'jhoblitt-ksm'
version '0.0.1'

author 'Joshua Hoblitt <jhoblitt@cpan.org>'
license 'Apache'
project_page 'https://github.com/jhoblitt/puppet-ksm'
source 'https://github.com/jhoblitt/puppet-ksm.git'
summary 'module skeleton'
description 'module skeleton'
dependency 'puppetlabs/stdlib', '>= 3.0.0'
dependency 'rodjek/logrotate', '>= 1.1.1'
