name    'jhoblitt-ksm'
version '0.0.1'

author 'Joshua Hoblitt <jhoblitt@cpan.org>'
license 'Apache'
project_page 'https://github.com/jhoblitt/puppet-ksm'
source 'https://github.com/jhoblitt/puppet-ksm.git'
summary 'Manages Linux Kernel Samepage Merging (KSM)'
description 'Manages Linux Kernel Samepage Merging (KSM)'
dependency 'puppetlabs/stdlib', '>= 4.0.0'
dependency 'rodjek/logrotate', '>= 1.1.1'
